/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.obleasnoob.view;

/**
 *
 * @author idea
 */
public class SalesForm extends javax.swing.JFrame {

    /**
     * Creates new form SalesForm
     */
    public SalesForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        generateExcel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        saleDate = new javax.swing.JTextField();
        fileName = new javax.swing.JTextField();
        targetRow = new javax.swing.JTextField();
        targetCol = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setMaximumSize(new java.awt.Dimension(808, 536));
        setMinimumSize(new java.awt.Dimension(808, 536));
        setPreferredSize(new java.awt.Dimension(808, 536));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(410, 80, 380, 10);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(10, 80, 380, 10);

        generateExcel.setBackground(new java.awt.Color(0, 0, 0));
        generateExcel.setForeground(new java.awt.Color(255, 255, 255));
        generateExcel.setText("Guardar");
        getContentPane().add(generateExcel);
        generateExcel.setBounds(700, 480, 73, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Ingresos operacionales");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 100, 170, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Costo de ventas");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 130, 170, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Utilidad bruta");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 160, 170, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Gastos de operaciones");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 190, 170, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("UAII");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 220, 170, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Ingresos no operacionales");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 250, 170, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Gastos no operacionales");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 280, 170, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Utilidad neta diaria");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 310, 170, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Horas por puestos");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 340, 170, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Total horas");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 370, 170, 15);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Utilidad por hora");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 400, 170, 15);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Nombre o ruta del archivo");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 20, 160, 17);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Fila proximo registro");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(410, 20, 160, 17);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Columna inicio de registro");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(560, 20, 160, 17);

        saleDate.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        saleDate.setToolTipText("saleDate");
        saleDate.setMaximumSize(new java.awt.Dimension(48, 20));
        saleDate.setMinimumSize(new java.awt.Dimension(48, 20));
        getContentPane().add(saleDate);
        saleDate.setBounds(200, 100, 180, 20);

        fileName.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        fileName.setToolTipText("saleDate");
        fileName.setMaximumSize(new java.awt.Dimension(48, 20));
        fileName.setMinimumSize(new java.awt.Dimension(48, 20));
        getContentPane().add(fileName);
        fileName.setBounds(20, 40, 370, 20);

        targetRow.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        targetRow.setToolTipText("saleDate");
        targetRow.setMaximumSize(new java.awt.Dimension(48, 20));
        targetRow.setMinimumSize(new java.awt.Dimension(48, 20));
        getContentPane().add(targetRow);
        targetRow.setBounds(410, 40, 120, 20);

        targetCol.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        targetCol.setToolTipText("saleDate");
        targetCol.setMaximumSize(new java.awt.Dimension(48, 20));
        targetCol.setMinimumSize(new java.awt.Dimension(48, 20));
        getContentPane().add(targetCol);
        targetCol.setBounds(560, 40, 120, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fileName;
    private javax.swing.JButton generateExcel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField saleDate;
    private javax.swing.JTextField targetCol;
    private javax.swing.JTextField targetRow;
    // End of variables declaration//GEN-END:variables
}
